version: '2'
services:
  gitbook:
    image: fellah/gitbook:3.2.0
    ports:
      - "4000:4000"
      - "35729:35729"
    volumes:
      - /Volumes/data/gitbook/gitbook:/srv/gitbook
      - /Volumes/data/gitbook/html:/srv/html
